# Generated by Django 4.2.11 on 2024-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="course",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
