# Generated by Django 4.2.11 on 2024-12-08 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_course_image_1_course_image_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="degree_awarded",
            new_name="awarded_by",
        ),
    ]
